/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Donor.UI;

import Patient.UI.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Gayatri
 */
public class DonorOrganDonate extends javax.swing.JPanel {

    /**
     * Creates new form PatientSendRequest
     */
    public DonorOrganDonate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        DonarSubmitBtn = new javax.swing.JButton();
        DonarKidneyBtn = new javax.swing.JButton();
        DonarEyesBtn = new javax.swing.JButton();
        DonarLiverBtn = new javax.swing.JButton();
        DonarPancreasBtn = new javax.swing.JButton();
        DonarIntestineBtn = new javax.swing.JButton();
        DonarLungBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("     Type Of Organ");

        DonarSubmitBtn.setBackground(new java.awt.Color(0, 204, 204));
        DonarSubmitBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        DonarSubmitBtn.setText("Submit");
        DonarSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarSubmitBtnActionPerformed(evt);
            }
        });

        DonarKidneyBtn.setText("KIDNEY");

        DonarEyesBtn.setText("EYES");
        DonarEyesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarEyesBtnActionPerformed(evt);
            }
        });

        DonarLiverBtn.setText("LIVER");

        DonarPancreasBtn.setText("PANCREAS");

        DonarIntestineBtn.setText("INTESTINE");
        DonarIntestineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarIntestineBtnActionPerformed(evt);
            }
        });

        DonarLungBtn.setText("LUNG");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DonarSubmitBtn)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DonarIntestineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DonarLiverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DonarKidneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DonarEyesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DonarPancreasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DonarLungBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(200, 234, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonarKidneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DonarEyesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DonarPancreasBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DonarLiverBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DonarLungBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DonarIntestineBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(DonarSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DonarSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarSubmitBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this," Request Submitted!");
    }//GEN-LAST:event_DonarSubmitBtnActionPerformed

    private void DonarEyesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarEyesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonarEyesBtnActionPerformed

    private void DonarIntestineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonarIntestineBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonarIntestineBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DonarEyesBtn;
    private javax.swing.JButton DonarIntestineBtn;
    private javax.swing.JButton DonarKidneyBtn;
    private javax.swing.JButton DonarLiverBtn;
    private javax.swing.JButton DonarLungBtn;
    private javax.swing.JButton DonarPancreasBtn;
    private javax.swing.JButton DonarSubmitBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
