/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hospital.UI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import model.ServiceHospital;

/**
 *
 * @author Gayatri
 */
public class HospitalPatientTable extends javax.swing.JPanel {

    /**
     * Creates new form HospitalPatientTable
     */
    
    String huser;
    String pass;
    Connection con;
    public HospitalPatientTable(String username, String password) throws SQLException {
        initComponents();
          huser = username;
          pass = password;
            String hname ="";
          try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 this.con=(Connection) DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/AED_DB","root","Snehal1&");  
                
                
            }
        catch(Exception e){ 
                System.out.println(e);
                
        }  
           Statement stmt = con.createStatement();
            String queryString = "SELECT hospital_name FROM hospital where hospital_username = '" + huser + "'" ;
            ResultSet results = stmt.executeQuery(queryString);

            while (results.next()) {
             hname = results.getString(1);

         
            }
            String queryString1 = "SELECT patient_hospitalname, patient_name, patient_community, patient_gender, patient_phonenumber,patient_emailid FROM patient where patient_hospitalname = '" + hname + "'";
            ResultSet results1 = stmt.executeQuery(queryString1);

            while (results1.next()) {
            String huname = results1.getString(1);
            String pname =  results1.getString(2);
            String pcommunity = results1.getString(3);
            String gender = results1.getString(4);
            String phonenumber = results1.getString(5);
            String emailid = results1.getString(6);
            System.out.println(hname +pname +emailid);
            String data[] = {pname, pcommunity, huname, gender, phonenumber,emailid};
            DefaultTableModel model = (DefaultTableModel) HospitalPatientTable.getModel();
            model.addRow(data);
            }
            
            String queryString2 = "SELECT patient_name, patient_requesttype, patient_requestvalue FROM patientrequests where hospital_username = '" + hname + "' and request_status = " + "'Open'";
            ResultSet results2 = stmt.executeQuery(queryString2);
            String pname;
            String retype;
            String reqvalue;
            while (results2.next()) {
             pname = results2.getString(1);
             retype = results2.getString(2);
             reqvalue = results2.getString(3);
             String data1[] = {pname, retype,reqvalue};
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             model.addRow(data1);
         
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HospitalPatientTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        HospitalPatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Community", "Hospital Name", "Gender", "Phone No.", "Email Id"
            }
        ));
        jScrollPane1.setViewportView(HospitalPatientTable);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("                  Patient Details ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Blood/Organ Type", "Blood/Organ Value"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable HospitalPatientTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}