/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Hospital.UI;

import Patient.UI.*;

import java.awt.event.KeyEvent;

import java.sql.SQLException;
import model.ServiceHospital;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Gayatri
 */
public class HospitalPersonalDetails extends javax.swing.JPanel {

    /**
     * Creates new form PatientRegistration1
     */
    String user;
    String pass;
    Connection con;
    public HospitalPersonalDetails(String username, String password) throws SQLException {
        
        initComponents();
         try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 this.con=(Connection) DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/AED_DB","root","Snehal1&");  
              
            }
        catch(Exception e){ 
                System.out.println(e);
                
        }
        user = username;
        pass = password;
        ServiceHospital sh = new ServiceHospital();
        sh.viewhtable(user,pass);
        
        Statement stmt = con.createStatement();
        String sql = "select * from hospital where hospital_username = '" + username + "' and hospital_password = '" + password+ "'"; 

            ResultSet results = stmt.executeQuery(sql);

            while (results.next()) {
            String name = results.getString(1);
            String uname =  results.getString(2);
            String pass = results.getString(3) ;
            String streetname = results.getString(4);
            String community = results.getString(5) ;
            String zipcode = results.getString(6) ;
            txtHospitalName.setText(name);
            txtHospitalUsername.setText(uname);
            txtHospitalPassword.setText(pass);
            txtHospitalStreet.setText(streetname);
            txtHospitalCommunity.setSelectedItem(community);
            txtHospitalZip.setText(zipcode);
            
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout1 = new javax.swing.JButton();
        HospitalUpdateBtn = new javax.swing.JButton();
        txtHospitalStreet = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        txtHospitalZip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHospitalCommunity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalUsername = new javax.swing.JTextField();
        txtHospitalPassword = new javax.swing.JTextField();

        Logout1.setBackground(new java.awt.Color(153, 0, 153));
        Logout1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logout1.setText("Back");
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 204, 204));

        HospitalUpdateBtn.setBackground(new java.awt.Color(0, 102, 102));
        HospitalUpdateBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HospitalUpdateBtn.setText("Update");
        HospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalUpdateBtnActionPerformed(evt);
            }
        });

        txtHospitalStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStreetActionPerformed(evt);
            }
        });
        txtHospitalStreet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalStreetKeyPressed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_title.setText("                Hospital Sign Up");

        txtHospitalZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalZipActionPerformed(evt);
            }
        });
        txtHospitalZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalZipKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("   Hospital Name:");

        txtHospitalCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allston", "Back Bay", "Bay Village", "Beacon Hill", "Brighton", "Charlestown", "Chinatown – Leather District", "Dorchester", "Downtown", "East Boston", "Fenway-Kenmore", "Hyde Park", "Jamaica Plain", "Mattapan", "Mid-Dorchester", "Mission Hill", "North End", "Roslindale", "Roxbury", "South Boston", "South End", "West End", "West Roxbury", " ", " ", " " }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("    Username:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("     Password:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Street Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText(" Community:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("      Zipcode: ");

        txtHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalNameActionPerformed(evt);
            }
        });
        txtHospitalName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalNameKeyPressed(evt);
            }
        });

        txtHospitalUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalUsernameActionPerformed(evt);
            }
        });

        txtHospitalPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(HospitalUpdateBtn)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(277, 277, 277)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(50, 50, 50)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtHospitalName)
                                .addComponent(txtHospitalUsername)
                                .addComponent(txtHospitalPassword)
                                .addComponent(txtHospitalStreet)
                                .addComponent(txtHospitalZip)
                                .addComponent(txtHospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHospitalUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHospitalPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHospitalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHospitalZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Logout1ActionPerformed

    private void HospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalUpdateBtnActionPerformed
        try {
            // TODO add your handling code here:
            String name =txtHospitalName.getText();
            String uname =txtHospitalUsername.getText();
            String pass = txtHospitalPassword.getText();
            String streetname = txtHospitalStreet.getText();
            String community = txtHospitalCommunity.getSelectedItem().toString();
            String zipcode = txtHospitalZip.getText();
            PreparedStatement stmt = con.prepareStatement("update hospital set hospital_name=?,hospital_password=?,hospital_streetname=?,hospital_community=?,hospital_zipcode=? where hospital_username=?");
            stmt.setString(1, name);
            stmt.setString(2, String.valueOf(pass));
            stmt.setString(3, String.valueOf(streetname));
            stmt.setString(4, String.valueOf(community));
            stmt.setString(5, String.valueOf(zipcode));
            stmt.setString(6, String.valueOf(uname));
            stmt.executeUpdate();
     
    }//GEN-LAST:event_HospitalUpdateBtnActionPerformed
    catch (SQLException ex) {
            Logger.getLogger(HospitalPersonalDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void txtHospitalStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStreetActionPerformed

    private void txtHospitalZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalZipActionPerformed

    private void txtHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalNameActionPerformed

    private void txtHospitalUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalUsernameActionPerformed

    private void txtHospitalPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalPasswordActionPerformed

    private void txtHospitalNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalNameKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter, space and isocontrol char than allow to edit
            txtHospitalName.setEditable(true);
        }else{
            txtHospitalName.setEditable(false);
        }
        
        
        
        
    }//GEN-LAST:event_txtHospitalNameKeyPressed

    private void txtHospitalStreetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalStreetKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter, space and isocontrol char than allow to edit
            txtHospitalStreet.setEditable(true);
        }else{
            txtHospitalStreet.setEditable(false);
        }
        
    }//GEN-LAST:event_txtHospitalStreetKeyPressed

    private void txtHospitalZipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalZipKeyPressed
        // TODO add your handling code here:
        
        String age= txtHospitalZip.getText();
        
        // get length of the string 
        int length = age.length();
        
        char c = evt.getKeyChar();
        
        //check for number 0 to 9 
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 10 digit 
            if(length<5){
                //editable true 
                txtHospitalZip.setEditable(true);
                //JOptionPane.showMessageDialog(this," Invalid Cell Number ");
                
            }else{
                //not editable if length is more than 10 digit
                txtHospitalZip.setEditable(false);
            }
        }else{
            //not allow keys 'backspace' and 'delete' for edit
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                //than allow editable 
                txtHospitalZip.setEditable(true);
            }else{
                txtHospitalZip.setEditable(false);
            }
        }
        
        
        
        
    }//GEN-LAST:event_txtHospitalZipKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HospitalUpdateBtn;
    private javax.swing.JButton Logout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JComboBox<String> txtHospitalCommunity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalPassword;
    private javax.swing.JTextField txtHospitalStreet;
    private javax.swing.JTextField txtHospitalUsername;
    private javax.swing.JTextField txtHospitalZip;
    // End of variables declaration//GEN-END:variables
}
