/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patient.UI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ServicePatient;

/**
 *
 * @author Gayatri
 */
public class PatientSendRequest extends javax.swing.JPanel {
        String organ = "";
        
    /**
     * Creates new form PatientSendRequest
     */
        
    String puser;
    String pass;
    public PatientSendRequest(String username, String password) {
        initComponents();
        
         puser = username;
         pass = password;
         
        System.out.println("logged in patient "+puser+ pass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PatientSendRequestBtn = new javax.swing.JButton();
        DonarKidneyBtn = new javax.swing.JButton();
        DonarEyesBtn = new javax.swing.JButton();
        DonarLiverBtn = new javax.swing.JButton();
        DonarPancreasBtn = new javax.swing.JButton();
        DonarIntestineBtn = new javax.swing.JButton();
        DonarLungBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Send Request For Organ");

        PatientSendRequestBtn.setBackground(new java.awt.Color(0, 102, 102));
        PatientSendRequestBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        PatientSendRequestBtn.setText("Send Request");
        PatientSendRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSendRequestBtnActionPerformed(evt);
            }
        });


        DonarKidneyBtn.setBackground(new java.awt.Color(255, 102, 153));
        DonarKidneyBtn.setText("KIDNEY");

        DonarEyesBtn.setBackground(new java.awt.Color(255, 153, 153));
        DonarEyesBtn.setText("EYES");

        DonarKidneyBtn.setText("KIDNEY");
        DonarKidneyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarKidneyBtnMouseClicked(evt);
            }
        });
        DonarKidneyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarKidneyBtnActionPerformed(evt);
            }
        });

        DonarEyesBtn.setText("EYES");
        DonarEyesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarEyesBtnMouseClicked(evt);
            }
        });
        DonarEyesBtn.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarEyesBtnActionPerformed(evt);
            }
        });

        DonarLiverBtn.setBackground(new java.awt.Color(255, 102, 0));
        DonarLiverBtn.setText("LIVER");

        DonarPancreasBtn.setBackground(new java.awt.Color(255, 204, 0));
        DonarPancreasBtn.setText("PANCREAS");

        DonarIntestineBtn.setBackground(new java.awt.Color(204, 0, 204));
        DonarIntestineBtn.setText("INTESTINE");

        DonarLiverBtn.setText("LIVER");
        DonarLiverBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarLiverBtnMouseClicked(evt);
            }
        });

        DonarPancreasBtn.setText("PANCREAS");
        DonarPancreasBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarPancreasBtnMouseClicked(evt);
            }
        });

        DonarIntestineBtn.setText("INTESTINE");
        DonarIntestineBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarIntestineBtnMouseClicked(evt);
            }
        });
        DonarIntestineBtn.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonarIntestineBtnActionPerformed(evt);
            }
        });


        DonarLungBtn.setBackground(new java.awt.Color(0, 153, 255));
        DonarLungBtn.setText("LUNG");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-kidney-vector-illustration-754700143 (2).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-human-eye-isolated-on-white-photo-realistic-vector-illustration-250674166 (1).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-realistic-liver-anatomy-structure-vector-hepatic-system-organ-digestive-gallbladder-organ-human-1794723994 (1).jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-pancreas-isolated-on-white-background-medicine-concept-flat-vector-cartoon-illustration-1911536488 (1).jpg"))); // NOI18N
        jLabel5.setText("jLabel5");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-human-intestines-organ-anatomy-medicine-concept-healthcare-internal-organs-of-the-human-design-1384580939 (1).jpg"))); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/stock-vector-lung-cancer-diagram-in-detail-illustration-308751308 (1).jpg"))); // NOI18N

        DonarLungBtn.setText("LUNG");
        DonarLungBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DonarLungBtnMouseClicked(evt);
            }
        });
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DonarLungBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DonarLiverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(DonarPancreasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DonarKidneyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(DonarEyesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(DonarIntestineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(467, 467, 467)
                        .addComponent(PatientSendRequestBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonarKidneyBtn)
                    .addComponent(DonarEyesBtn))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DonarLiverBtn)
                    .addComponent(DonarPancreasBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DonarLungBtn)
                    .addComponent(DonarIntestineBtn))
                .addGap(50, 50, 50)
                .addComponent(PatientSendRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void PatientSendRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        if(this.organ.equals("")){
            
        JOptionPane.showMessageDialog(this," Please select a organ");
        }
        else{
            try {
                ServicePatient s1 = new ServicePatient();
                s1.sendOrganRequest(puser,pass,organ);
            } catch (SQLException ex) {
                Logger.getLogger(PatientSendRequest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        JOptionPane.showMessageDialog(this," Request Submitted!");
    }                                                     

    private void DonarEyesBtnActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:

    }                                            

    
                                                 


    private void DonarIntestineBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:

    }                                                 

     
                                                 

    private void DonarKidneyBtnMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
        
        this.organ = "Kidney";
        
        
        
        
    }                                             


    private void DonarKidneyBtnActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void DonarEyesBtnMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        this.organ = "Eyes";
    }                                           

    private void DonarLiverBtnMouseClicked(java.awt.event.MouseEvent evt) {                                             
        // TODO add your handling code here:
        this.organ = "Liver";
    }                                            

    private void DonarPancreasBtnMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
        this.organ = "Pancreas";
    }                                               

    private void DonarIntestineBtnMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        // TODO add your handling code here:
        this.organ = "Intestine";
    }                                                

    private void DonarLungBtnMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        this.organ = "Lungs";
    }                                           


    // Variables declaration - do not modify                     
    private javax.swing.JButton DonarEyesBtn;
    private javax.swing.JButton DonarIntestineBtn;
    private javax.swing.JButton DonarKidneyBtn;
    private javax.swing.JButton DonarLiverBtn;
    private javax.swing.JButton DonarLungBtn;
    private javax.swing.JButton DonarPancreasBtn;
    private javax.swing.JButton PatientSendRequestBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration                   
}
