/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patient.UI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ServicePatient;

/**
 *
 * @author Gayatri
 */
public class PatientSendRequest extends javax.swing.JPanel {
        String organ = "";
        
    /**
     * Creates new form PatientSendRequest
     */
        
    String puser;
    String pass;
    public PatientSendRequest(String username, String password) {
        initComponents();
        
         puser = username;
         pass = password;
         
        System.out.println("logged in patient "+puser+ pass);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PatientSendRequestBtn = new javax.swing.JButton();
        KidneyRequestBtn = new javax.swing.JButton();
        EyesRequestBtn = new javax.swing.JButton();
        LiverRequestBtn = new javax.swing.JButton();
        PancreasRequestBtn = new javax.swing.JButton();
        IntestineRequestBtn = new javax.swing.JButton();
        LungRequestBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Send Request For Organ");

        PatientSendRequestBtn.setBackground(new java.awt.Color(0, 204, 204));
        PatientSendRequestBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        PatientSendRequestBtn.setText("Send Request");
        PatientSendRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientSendRequestBtnActionPerformed(evt);
            }
        });

        KidneyRequestBtn.setText("KIDNEY");
        KidneyRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                KidneyRequestBtnMouseClicked(evt);
            }
        });
        KidneyRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KidneyRequestBtnActionPerformed(evt);
            }
        });

        EyesRequestBtn.setText("EYES");
        EyesRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EyesRequestBtnMouseClicked(evt);
            }
        });
        EyesRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EyesRequestBtnActionPerformed(evt);
            }
        });

        LiverRequestBtn.setText("LIVER");
        LiverRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LiverRequestBtnMouseClicked(evt);
            }
        });

        PancreasRequestBtn.setText("PANCREAS");
        PancreasRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PancreasRequestBtnMouseClicked(evt);
            }
        });

        IntestineRequestBtn.setText("INTESTINE");
        IntestineRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IntestineRequestBtnMouseClicked(evt);
            }
        });
        IntestineRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntestineRequestBtnActionPerformed(evt);
            }
        });

        LungRequestBtn.setText("LUNG");
        LungRequestBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LungRequestBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PatientSendRequestBtn)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IntestineRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LiverRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(KidneyRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(EyesRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PancreasRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LungRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KidneyRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EyesRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PancreasRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LiverRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LungRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IntestineRequestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(PatientSendRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PatientSendRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientSendRequestBtnActionPerformed
        // TODO add your handling code here:
        if(this.organ.equals("")){
            
        JOptionPane.showMessageDialog(this," Please select a organ");
        }
        else{
            try {
                ServicePatient s1 = new ServicePatient();
                s1.sendOrganRequest(puser,pass,organ);
            } catch (SQLException ex) {
                Logger.getLogger(PatientSendRequest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
        JOptionPane.showMessageDialog(this," Request Submitted!");
    }//GEN-LAST:event_PatientSendRequestBtnActionPerformed

    private void EyesRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EyesRequestBtnActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_EyesRequestBtnActionPerformed

    private void IntestineRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntestineRequestBtnActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_IntestineRequestBtnActionPerformed

    private void KidneyRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_KidneyRequestBtnMouseClicked
        // TODO add your handling code here:
        
        this.organ = "Kidney";
        
        
        
        
    }//GEN-LAST:event_KidneyRequestBtnMouseClicked

    private void KidneyRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KidneyRequestBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KidneyRequestBtnActionPerformed

    private void EyesRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EyesRequestBtnMouseClicked
        // TODO add your handling code here:
        this.organ = "Eyes";
    }//GEN-LAST:event_EyesRequestBtnMouseClicked

    private void LiverRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LiverRequestBtnMouseClicked
        // TODO add your handling code here:
        this.organ = "Liver";
    }//GEN-LAST:event_LiverRequestBtnMouseClicked

    private void PancreasRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PancreasRequestBtnMouseClicked
        // TODO add your handling code here:
        this.organ = "Pancreas";
    }//GEN-LAST:event_PancreasRequestBtnMouseClicked

    private void IntestineRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IntestineRequestBtnMouseClicked
        // TODO add your handling code here:
        this.organ = "Intestine";
    }//GEN-LAST:event_IntestineRequestBtnMouseClicked

    private void LungRequestBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LungRequestBtnMouseClicked
        // TODO add your handling code here:
        this.organ = "Lungs";
    }//GEN-LAST:event_LungRequestBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EyesRequestBtn;
    private javax.swing.JButton IntestineRequestBtn;
    private javax.swing.JButton KidneyRequestBtn;
    private javax.swing.JButton LiverRequestBtn;
    private javax.swing.JButton LungRequestBtn;
    private javax.swing.JButton PancreasRequestBtn;
    private javax.swing.JButton PatientSendRequestBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
