/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Administration.UI;

import Hospital.UI.*;
import Patient.UI.*;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ServiceHospital;
import model.hospital.Hospital;

/**
 *
 * @author Gayatri
 */
public class AdminHospitalManagePage extends javax.swing.JPanel {

    /**
     * Creates new form PatientRegistration1
     */
    String selectedhname;
    String selectedstreetname,selectedcommunity,selectedzipcode;
    Connection con;
    public AdminHospitalManagePage() throws SQLException {
        initComponents();
    
    try{  
                Class.forName("com.mysql.jdbc.Driver");  
                 this.con=(Connection) DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/AED_DB","root","Snehal1&");  
                
                
            }
        catch(Exception e){ 
                System.out.println(e);
                
        }  
           Statement stmt = con.createStatement();
           
            String queryString1 = "SELECT hospital_name, hospital_streetname, hospital_community, hospital_zipcode from hospital";
      
            ResultSet results1 = stmt.executeQuery(queryString1);

            while (results1.next()) {
            String huname = results1.getString(1);
            String streetname =  results1.getString(2);
            String pcommunity = results1.getString(3);
            String zipcode = results1.getString(4);
            String data[] = {huname, streetname, pcommunity, zipcode};
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(data);
            }
            
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logout1 = new javax.swing.JButton();
        HospitalUpdateBtn = new javax.swing.JButton();
        txtHospitalStreet = new javax.swing.JTextField();
        lbl_title = new javax.swing.JLabel();
        txtHospitalZip = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtHospitalCommunity = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtHospitalName = new javax.swing.JTextField();
        txtHospitalUsername = new javax.swing.JTextField();
        txtHospitalPassword = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        HospitalUpdateBtn2 = new javax.swing.JButton();

        Logout1.setBackground(new java.awt.Color(153, 0, 153));
        Logout1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Logout1.setText("Back");
        Logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Logout1ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(0, 204, 204));

        HospitalUpdateBtn.setBackground(new java.awt.Color(0, 204, 204));
        HospitalUpdateBtn.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HospitalUpdateBtn.setText("Save");
        HospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalUpdateBtnActionPerformed(evt);
            }
        });

        txtHospitalStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalStreetActionPerformed(evt);
            }
        });
        txtHospitalStreet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalStreetKeyPressed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_title.setText("                     Hospital Details");

        txtHospitalZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalZipActionPerformed(evt);
            }
        });
        txtHospitalZip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalZipKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("   Hospital Name:");

        txtHospitalCommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Allston", "Back Bay", "Bay Village", "Beacon Hill", "Brighton", "Charlestown", "Chinatown – Leather District", "Dorchester", "Downtown", "East Boston", "Fenway-Kenmore", "Hyde Park", "Jamaica Plain", "Mattapan", "Mid-Dorchester", "Mission Hill", "North End", "Roslindale", "Roxbury", "South Boston", "South End", "West End", "West Roxbury", " ", " ", " " }));
        txtHospitalCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalCommunityActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("    Username:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("     Password:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Street Name:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText(" Community:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("      Zipcode: ");

        txtHospitalName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalNameActionPerformed(evt);
            }
        });
        txtHospitalName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHospitalNameKeyPressed(evt);
            }
        });

        txtHospitalUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalUsernameActionPerformed(evt);
            }
        });

        txtHospitalPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHospitalPasswordActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Hospital Name", "Street Name", "Community", "Zipcode"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        HospitalUpdateBtn2.setBackground(new java.awt.Color(0, 204, 204));
        HospitalUpdateBtn2.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        HospitalUpdateBtn2.setText("Delete");
        HospitalUpdateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HospitalUpdateBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HospitalUpdateBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtHospitalName)
                                    .addComponent(txtHospitalUsername)
                                    .addComponent(txtHospitalPassword)
                                    .addComponent(txtHospitalStreet)
                                    .addComponent(txtHospitalZip)
                                    .addComponent(txtHospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 826, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(626, 626, 626)
                        .addComponent(HospitalUpdateBtn2)))
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_title)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtHospitalUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHospitalPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHospitalStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtHospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtHospitalZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(HospitalUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(HospitalUpdateBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Logout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Logout1ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_Logout1ActionPerformed

    private void HospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalUpdateBtnActionPerformed
        try {
            // TODO add your handling code here:
            
            
            if(txtHospitalName.getText().equals("") || txtHospitalPassword.getText().equals("")
                    || txtHospitalStreet.getText().equals("") || txtHospitalUsername.getText().equals("") ||
                    txtHospitalZip.getText().equals("") ){
                
                JOptionPane.showMessageDialog(this," All details are not Filled ");
                
            }
            else
            {
                
                try {
                    JOptionPane.showMessageDialog(this," New Hospital Added ");
                    Hospital h = new Hospital();
                    h.setHname(txtHospitalName.getText());
                    h.setHusername(txtHospitalUsername.getText());
                    h.setHpassword(txtHospitalPassword.getText());
                    h.setHstreetname(txtHospitalStreet.getText());
                    h.setHcommunity(txtHospitalCommunity.getSelectedItem().toString());
                    h.setHzipcode(Integer.parseInt(txtHospitalZip.getText()));
                    System.out.println(h.getHname());
                    ServiceHospital s1 = new ServiceHospital();
                    s1.addhospitaldetails(h);
                    
                    
                    txtHospitalName.setText("");
                    txtHospitalUsername.setText("");
                    txtHospitalPassword.setText("");
                    txtHospitalStreet.setText("");
                    txtHospitalZip.setText("");
                } catch (SQLException ex) {
                    Logger.getLogger(AdminHospitalManagePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            String queryString1 = "SELECT hospital_name, hospital_streetname, hospital_community, hospital_zipcode from hospital";
            
            Statement stmt = con.createStatement();
            ResultSet results1 = stmt.executeQuery(queryString1);
             DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             while (model.getRowCount()>0)
          {
             model.removeRow(0);
          }
            while (results1.next()) {
                String huname = results1.getString(1);
                String streetname =  results1.getString(2);
                String pcommunity = results1.getString(3);
                String zipcode = results1.getString(4);
                String data[] = {huname, streetname, pcommunity, zipcode};
                 model = (DefaultTableModel) jTable1.getModel();
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AdminHospitalManagePage.class.getName()).log(Level.SEVERE, null, ex);
        }
             
        
        
    }//GEN-LAST:event_HospitalUpdateBtnActionPerformed
    
    
    private void txtHospitalStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalStreetActionPerformed

    private void txtHospitalZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalZipActionPerformed

    private void txtHospitalNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalNameActionPerformed

    private void txtHospitalUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalUsernameActionPerformed

    private void txtHospitalPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalPasswordActionPerformed

    private void txtHospitalNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalNameKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter, space and isocontrol char than allow to edit
            txtHospitalName.setEditable(true);
        }else{
            txtHospitalName.setEditable(false);
        }
        
        
        
        
    }//GEN-LAST:event_txtHospitalNameKeyPressed

    private void txtHospitalStreetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalStreetKeyPressed
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if(Character.isLetter(c) || Character.isWhitespace(c) || Character.isISOControl(c)){
            //iso control for edit operation(delete key and backspace key allow)
            //if enter character is letter, space and isocontrol char than allow to edit
            txtHospitalStreet.setEditable(true);
        }else{
            txtHospitalStreet.setEditable(false);
        }
        
    }//GEN-LAST:event_txtHospitalStreetKeyPressed

    private void txtHospitalZipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHospitalZipKeyPressed
        // TODO add your handling code here:
        
        String age= txtHospitalZip.getText();
        
        // get length of the string 
        int length = age.length();
        
        char c = evt.getKeyChar();
        
        //check for number 0 to 9 
        if(evt.getKeyChar()>='0' && evt.getKeyChar()<='9'){
            //check for length not more than 10 digit 
            if(length<5){
                //editable true 
                txtHospitalZip.setEditable(true);
                //JOptionPane.showMessageDialog(this," Invalid Cell Number ");
                
            }else{
                //not editable if length is more than 10 digit
                txtHospitalZip.setEditable(false);
            }
        }else{
            //not allow keys 'backspace' and 'delete' for edit
            if(evt.getExtendedKeyCode()== KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode()== KeyEvent.VK_DELETE){
                //than allow editable 
                txtHospitalZip.setEditable(true);
            }else{
                txtHospitalZip.setEditable(false);
            }
        }
        
        
        
        
    }//GEN-LAST:event_txtHospitalZipKeyPressed

    private void txtHospitalCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHospitalCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHospitalCommunityActionPerformed

    private void HospitalUpdateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HospitalUpdateBtn2ActionPerformed
           
        try {                                                   
                Statement stmt = con.createStatement();
                try {
                    // TODO add your handling code here:
                    
                    
                    
                    String sql = "DELETE FROM hospital where hospital_name = '" +selectedhname+"' and hospital_streetname = '"+selectedstreetname+"' and hospital_community = '" +selectedcommunity+ "' and hospital_zipcode = '" +selectedzipcode +"'";
                    int i = stmt.executeUpdate(sql);
                    System.out.println(sql);
                    System.out.println("updated rows"+i);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminHospitalManagePage.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "Hospital record deleted");
                String queryString1 = "SELECT hospital_name, hospital_streetname, hospital_community, hospital_zipcode from hospital";
                
                
                ResultSet results1 = stmt.executeQuery(queryString1);
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                while (model.getRowCount()>0)
                {
                    model.removeRow(0);
                }
                while (results1.next()) {
                    String huname = results1.getString(1);
                    String streetname =  results1.getString(2);
                    String pcommunity = results1.getString(3);
                    String zipcode = results1.getString(4);
                    String data[] = {huname, streetname, pcommunity, zipcode};
                    model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(data);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(AdminHospitalManagePage.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_HospitalUpdateBtn2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel tblmodel = (DefaultTableModel) jTable1.getModel();
        
          selectedhname = tblmodel.getValueAt(jTable1.getSelectedRow(),0).toString();
          selectedstreetname = tblmodel.getValueAt(jTable1.getSelectedRow(),1).toString();
          selectedcommunity = tblmodel.getValueAt(jTable1.getSelectedRow(),2).toString();
          selectedzipcode = tblmodel.getValueAt(jTable1.getSelectedRow(),3).toString();
        
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HospitalUpdateBtn;
    private javax.swing.JButton HospitalUpdateBtn2;
    private javax.swing.JButton Logout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JComboBox<String> txtHospitalCommunity;
    private javax.swing.JTextField txtHospitalName;
    private javax.swing.JTextField txtHospitalPassword;
    private javax.swing.JTextField txtHospitalStreet;
    private javax.swing.JTextField txtHospitalUsername;
    private javax.swing.JTextField txtHospitalZip;
    // End of variables declaration//GEN-END:variables
}
